name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install React
      run: npx create-react-app my-app

    - name: Build project
      run: npm run build

    - name: Check for test files
      id: check_test_files
      run: |
        if ls src/**/*.test.js 1> /dev/null 2>&1; then
          echo "tests_exist=true" >> $GITHUB_ENV
        else
          echo "tests_exist=false" >> $GITHUB_ENV
        fi

    - name: Run tests
      if: env.tests_exist == 'true'
      run: npm test